# Generated by Django 3.1.5 on 2021-04-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_artimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tools',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
