# Generated by Django 3.1.5 on 2021-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_totallikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='arttype',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
