# Generated by Django 3.1.5 on 2021-04-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_arttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='arttype',
            field=models.CharField(max_length=255),
        ),
    ]
