# Generated by Django 3.1.5 on 2021-04-20 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_artlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artlike',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
