# Generated by Django 3.1.5 on 2021-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210420_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artlike',
            name='likes',
        ),
        migrations.AddField(
            model_name='artlike',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
