# Generated by Django 3.1.5 on 2021-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210420_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artlike',
            name='likes',
        ),
        migrations.AlterField(
            model_name='artlike',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
